services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=MyElm'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=123456'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306:3306'
  redis:
    image: 'redis:latest'
    environment:
      - 'REDIS_PASSWORD=12345678'
    ports:
      - '6379:6379'
