spring:
  application:
    name: medium-elm
  datasource:
    url: jdbc:mysql://localhost:3306/MyElm&allowMultiQueries=true
    username: root
    password: 123456
  security:
    filter:
      order: -100
    jwt:
      key: abcdefghijk
      expire: 7
    user:
      name: root
      password: 123456
  mail:
    host: smtp.qq.com
    username: 2625056626@qq.com
    password: jommybroiler666
  rabbitmq:
    addresses: localhost
    username: root
    password: 12345678
    virtual-host: /
springdoc:
  swagger-ui:
    path: /doc/ui
  api-docs:
    path: /doc/json
server:
  port: 8080
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl